const head = document.querySelector('head');
const link1 = document.createElement('link');
link1.setAttribute('rel', 'stylesheet');
link1.setAttribute('href', 'https://site-assets.fontawesome.com/releases/v6.4.0/css/all.css');
head.appendChild(link1);
const link2 = document.createElement('link');
link2.setAttribute('rel', 'stylesheet');
link2.setAttribute('href', 'https://site-assets.fontawesome.com/releases/v6.4.0/css/sharp-solid.css');
head.appendChild(link2);
const link3 = document.createElement('link');
link3.setAttribute('rel', 'stylesheet');
link3.setAttribute('href', 'https://site-assets.fontawesome.com/releases/v6.4.0/css/sharp-regular.css');
head.appendChild(link3);
